# Generated by Django 5.2.5 on 2025-09-15 10:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(99999999)])),
                ('movie_title', models.CharField(max_length=200, verbose_name='Title')),
                ('actor1_name', models.CharField(blank=True, max_length=100, verbose_name='Actor 1')),
                ('actor2_name', models.CharField(blank=True, max_length=100, verbose_name='Actor 2')),
                ('director_name', models.CharField(blank=True, max_length=100, verbose_name='Director')),
                ('movie_genre', models.CharField(choices=[('COM', 'Comedy'), ('ROM', 'Romance'), ('ACT', 'Action'), ('DRM', 'Drama'), ('HOR', 'Horror'), ('OTH', 'Other')], default='OTH', max_length=10, verbose_name='Genre')),
                ('release_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1888), django.core.validators.MaxValueValidator(2026)], verbose_name='Release Year')),
                ('DurationMinutes', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(600)])),
                ('Country', models.CharField(max_length=50)),
                ('Rating', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
    ]
